<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
        <!ELEMENT root (element)*>
        <!ELEMENT element (hardware|id_del_equipo|lista_software|marca_del_equipo|sistema_operativo|tipo_de_equipo|uso_del_equipo)*>
        <!ELEMENT hardware (Cantidad_memoria_GB|HDD|pantalla|procesador|velocidad_memoria_GBs)*>
        <!ELEMENT Cantidad_memoria_GB (#PCDATA)>
        <!ELEMENT HDD (capacidad|tipo)*>
        <!ELEMENT capacidad (#PCDATA)>
        <!ELEMENT tipo (#PCDATA)>
        <!ELEMENT pantalla (diagonal|resolucion)*>
        <!ELEMENT diagonal (#PCDATA)>
        <!ELEMENT resolucion (#PCDATA)>
        <!ELEMENT procesador (#PCDATA)>
        <!ELEMENT velocidad_memoria_GBs (#PCDATA)>
        <!ELEMENT id_del_equipo (#PCDATA)>
        <!ELEMENT lista_software (Libre|Pago)*>
        <!ELEMENT Libre (nombre_software|version)*>
        <!ELEMENT nombre_software (#PCDATA)>
        <!ELEMENT version (#PCDATA)>
        <!ELEMENT Pago (nombre_software|tipo|version)*>
        <!ELEMENT marca_del_equipo (#PCDATA)>
        <!ELEMENT sistema_operativo (nombre|version)*>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT tipo_de_equipo (#PCDATA)>
        <!ELEMENT uso_del_equipo (#PCDATA)>
        ]>
<root>
    <element>
        <hardware>
            <Cantidad_memoria_GB>3.5</Cantidad_memoria_GB>
            <HDD>
                <capacidad>10PB</capacidad>
                <tipo>HDD</tipo>
            </HDD>
            <pantalla>
                <diagonal>23.4</diagonal>
                <resolucion>32.3</resolucion>
            </pantalla>
            <procesador>Sobremesa</procesador>
            <velocidad_memoria_GBs>0.12</velocidad_memoria_GBs>
        </hardware>
        <id_del_equipo>0</id_del_equipo>
        <lista_software>
            <Libre>
                <nombre_software>Fornite</nombre_software>
                <version>2021</version>
            </Libre>
            <Pago>
                <nombre_software>Fornite_skins</nombre_software>
                <tipo>Estetico</tipo>
                <version>2021</version>
            </Pago>
        </lista_software>
        <marca_del_equipo>AlienX</marca_del_equipo>
        <sistema_operativo>
            <nombre>Windows</nombre>
            <version>3</version>
        </sistema_operativo>
        <tipo_de_equipo>Sobremesa</tipo_de_equipo>
        <uso_del_equipo>Pa jugar al fornite</uso_del_equipo>
    </element>
    <element>
        <hardware>
            <Cantidad_memoria_GB>2.5</Cantidad_memoria_GB>
            <HDD>
                <capacidad>10PB</capacidad>
                <tipo>HDD</tipo>
            </HDD>
            <pantalla>
                <diagonal>23.4</diagonal>
                <resolucion>32.3</resolucion>
            </pantalla>
            <procesador>Pentium II</procesador>
            <velocidad_memoria_GBs>1.12</velocidad_memoria_GBs>
        </hardware>
        <id_del_equipo>1</id_del_equipo>
        <lista_software>
            <Libre>
                <nombre_software>Paint</nombre_software>
                <version>2021</version>
            </Libre>
            <Pago>
                <nombre_software>Word</nombre_software>
                <tipo>Presentaciones</tipo>
                <version>2016</version>
            </Pago>
        </lista_software>
        <marca_del_equipo>Chuwi</marca_del_equipo>
        <sistema_operativo>
            <nombre>Debian</nombre>
            <version>2</version>
        </sistema_operativo>
        <tipo_de_equipo>Portatil</tipo_de_equipo>
        <uso_del_equipo>Redacción de informes y documentación</uso_del_equipo>
    </element>
    <element>
        <hardware>
            <Cantidad_memoria_GB>3.5</Cantidad_memoria_GB>
            <HDD>
                <capacidad>10PB</capacidad>
                <tipo>HDD</tipo>
            </HDD>
            <pantalla>
                <diagonal>23.4</diagonal>
                <resolucion>32.3</resolucion>
            </pantalla>
            <procesador>PentiumI</procesador>
            <velocidad_memoria_GBs>0.12</velocidad_memoria_GBs>
        </hardware>
        <id_del_equipo>2</id_del_equipo>
        <lista_software>
            <Libre>
                <nombre_software>Paint</nombre_software>
                <version>2021</version>
            </Libre>
            <Pago>
                <nombre_software>Powerpoint</nombre_software>
                <tipo>Presentaciones</tipo>
                <version>2016</version>
            </Pago>
        </lista_software>
        <marca_del_equipo>Blanca</marca_del_equipo>
        <sistema_operativo>
            <nombre>Ubuntu 365</nombre>
            <version>3</version>
        </sistema_operativo>
        <tipo_de_equipo>Sobremesa</tipo_de_equipo>
        <uso_del_equipo>Bastnate (varios fines)</uso_del_equipo>
    </element>
    <element>
        <hardware>
            <Cantidad_memoria_GB>5.5</Cantidad_memoria_GB>
            <HDD>
                <capacidad>5PB</capacidad>
                <tipo>HDD</tipo>
            </HDD>
            <pantalla>
                <diagonal>23.4</diagonal>
                <resolucion>32.3</resolucion>
            </pantalla>
            <procesador>Intel Celerón</procesador>
            <velocidad_memoria_GBs>1.12</velocidad_memoria_GBs>
        </hardware>
        <id_del_equipo>3</id_del_equipo>
        <lista_software>
            <Libre>
                <nombre_software>2.3</nombre_software>
                <version>2014</version>
            </Libre>
            <Pago>
                <nombre_software>IntelliJ</nombre_software>
                <tipo>Programación Java</tipo>
                <version>2019</version>
            </Pago>
        </lista_software>
        <marca_del_equipo>Huawey</marca_del_equipo>
        <sistema_operativo>
            <nombre>Windows</nombre>
            <version>Vista</version>
        </sistema_operativo>
        <tipo_de_equipo>Portatil</tipo_de_equipo>
        <uso_del_equipo>Programación de API's</uso_del_equipo>
    </element>
</root>